<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Ant\MediaBundle\Entity;

use Ant\WebBundle\Entity\Category;
use Sonata\MediaBundle\Entity\BaseGallery as BaseGallery;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\ArrayCollection;
/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Gallery extends BaseGallery
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string $link
     *
     */
    private $link;

    /**
     * @var string $description
     *
     */
    protected $description;

    /**
     * @Gedmo\Slug(fields={"title"})
     *
     */
    protected $slug;


    /**
     * @var string $category
     *
     */
    protected $category;

    private $categories;


    public function __construct() {
        $this->categories = new ArrayCollection();
    }

    public function addCategories(Category $category)
    {
        $category->addGallery($this); // synchronously updating inverse side
        $this->categories[] = $category;
    }



    public function setCategories ($categories) {
        $this->categories = $categories;
        return $this;
    }

    public function getCategories(){
        return $this->categories;
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function setDescription($description){
        $this->description = $description;
        return $this;
    }


    /**
     * Get Description
     *
     * @return string $description
     */
    public function getDescription(){
        return $this->description;
    }


    public function setLink ($link) {
        $this->link = $link;
        return $this;
    }

    public function getLink(){
        return $this->link;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * {@inheritdoc}
     */
    public function __toString()
    {
        return $this->getName() ?: '-';
    }


}